import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { LogOut, Package, FileText, Pencil, Trash2, Trash, User, Lock, ArrowLeft } from "lucide-react";
import type { Product } from "@shared/schema";

export default function AdminPage() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [loginData, setLoginData] = useState({ username: "", password: "" });
  const [isLoading, setIsLoading] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [isAddingProduct, setIsAddingProduct] = useState(false);
  const [isAddingUser, setIsAddingUser] = useState(false);
  const [editingUser, setEditingUser] = useState<any>(null);
  const [isChangingPassword, setIsChangingPassword] = useState(false);
  const [currentUser, setCurrentUser] = useState<any>(null);
  const [newProductName, setNewProductName] = useState("");
  const [autoGeneratedAbbrev, setAutoGeneratedAbbrev] = useState("");
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: products, isLoading: productsLoading } = useQuery({
    queryKey: ["/api/products"],
    enabled: isLoggedIn,
  });

  const { data: users, isLoading: usersLoading } = useQuery({
    queryKey: ["/api/admin/users"],
    enabled: isLoggedIn,
  });

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      const response = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(loginData),
      });

      if (response.ok) {
        setIsLoggedIn(true);
        toast({ title: "Login successful" });
      } else {
        toast({ title: "Login failed", variant: "destructive" });
      }
    } catch (error) {
      toast({ title: "Login error", variant: "destructive" });
    } finally {
      setIsLoading(false);
    }
  };

  const handleLogout = async () => {
    try {
      await fetch("/api/auth/logout", { method: "POST" });
      setIsLoggedIn(false);
      toast({ title: "Logged out successfully" });
    } catch (error) {
      console.error("Logout error:", error);
    }
  };

  const updateProductMutation = useMutation({
    mutationFn: async (data: { id: number; updates: any }) => {
      const response = await fetch(`/api/admin/products/${data.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data.updates),
      });
      if (!response.ok) throw new Error("Failed to update product");
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/products"] });
      setEditingProduct(null);
      toast({ title: "Product updated successfully" });
    },
    onError: () => {
      toast({ title: "Failed to update product", variant: "destructive" });
    },
  });

  const createProductMutation = useMutation({
    mutationFn: async (productData: any) => {
      const response = await fetch("/api/admin/products", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(productData),
      });
      if (!response.ok) throw new Error("Failed to create product");
      return response.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/products"] });
      setIsAddingProduct(false);
      toast({ title: "Product created successfully" });
    },
    onError: () => {
      toast({ title: "Failed to create product", variant: "destructive" });
    },
  });

  const generateShortcode = (name: string, existingProducts: any[] = []): string => {
    const existingAbbreviations = new Set(
      existingProducts.map(p => p.abbreviation.toLowerCase())
    );

    // Clean and split the name
    const words = name.trim().split(/\s+/).filter(word => word.length > 0);
    
    if (words.length === 0) return "Xx";

    // Try different strategies to generate a 2-character abbreviation
    const strategies = [
      // Strategy 1: First letter of first two words (capitalized)
      () => {
        if (words.length >= 2) {
          return words[0][0].toUpperCase() + words[1][0].toLowerCase();
        }
        return null;
      },
      
      // Strategy 2: First letter + second letter of first word
      () => {
        if (words[0].length >= 2) {
          return words[0][0].toUpperCase() + words[0][1].toLowerCase();
        }
        return null;
      },
      
      // Strategy 3: First letter + first consonant of first word
      () => {
        const consonants = words[0].slice(1).match(/[bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ]/);
        if (consonants) {
          return words[0][0].toUpperCase() + consonants[0].toLowerCase();
        }
        return null;
      },
      
      // Strategy 4: Try combinations from multiple words
      () => {
        if (words.length >= 2) {
          for (let i = 0; i < words[0].length && i < 2; i++) {
            for (let j = 0; j < words[1].length && j < 2; j++) {
              const combo = words[0][i].toUpperCase() + words[1][j].toLowerCase();
              if (!existingAbbreviations.has(combo.toLowerCase())) {
                return combo;
              }
            }
          }
        }
        return null;
      },
      
      // Strategy 5: Try different letter combinations from single word
      () => {
        const word = words[0];
        for (let i = 0; i < word.length - 1; i++) {
          for (let j = i + 1; j < word.length; j++) {
            const combo = word[i].toUpperCase() + word[j].toLowerCase();
            if (!existingAbbreviations.has(combo.toLowerCase())) {
              return combo;
            }
          }
        }
        return null;
      },
      
      // Strategy 6: Add numbers if all else fails
      () => {
        const base = words[0][0].toUpperCase() + (words[0][1] || words[1]?.[0] || 'x').toLowerCase();
        for (let i = 1; i <= 99; i++) {
          const combo = base.slice(0, 1) + i.toString().padStart(1, '0');
          if (!existingAbbreviations.has(combo.toLowerCase())) {
            return combo;
          }
        }
        return base;
      }
    ];

    // Try each strategy until we find an unused abbreviation
    for (const strategy of strategies) {
      const result = strategy();
      if (result && !existingAbbreviations.has(result.toLowerCase())) {
        return result;
      }
    }

    // Fallback - should never reach here
    return words[0][0].toUpperCase() + "x";
  };

  const handleProductSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const productData = {
      name: formData.get("name") as string,
      abbreviation: formData.get("abbreviation") as string,
      description: formData.get("description") as string,
      category: formData.get("category") as string,
      status: formData.get("status") as string,
      url: formData.get("url") as string || null,
    };

    if (editingProduct) {
      updateProductMutation.mutate({ id: editingProduct.id, updates: productData });
    } else if (isAddingProduct) {
      createProductMutation.mutate(productData);
    }
  };

  const handleAddNewProduct = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const productData = {
      name: formData.get("name") as string,
      abbreviation: formData.get("abbreviation") as string,
      description: formData.get("description") as string,
      category: formData.get("category") as string,
      status: formData.get("status") as string,
      url: formData.get("url") as string || null,
    };

    createProductMutation.mutate(productData);
  };

  // User management functions
  const handleDeleteUser = async (userId: number) => {
    if (window.confirm("Are you sure you want to delete this user?")) {
      try {
        const response = await fetch(`/api/admin/users/${userId}`, {
          method: "DELETE",
        });
        if (response.ok) {
          queryClient.invalidateQueries({ queryKey: ["/api/admin/users"] });
          toast({ title: "User deleted successfully" });
        } else {
          throw new Error("Failed to delete user");
        }
      } catch (error) {
        toast({ title: "Failed to delete user", variant: "destructive" });
      }
    }
  };

  const handleUserSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const userData = {
      username: formData.get("username") as string,
      email: formData.get("email") as string,
      role: formData.get("role") as string,
    };

    try {
      const response = await fetch("/api/admin/users", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(userData),
      });

      if (response.ok) {
        const result = await response.json();
        queryClient.invalidateQueries({ queryKey: ["/api/admin/users"] });
        setIsAddingUser(false);
        toast({ 
          title: "User created successfully",
          description: result.emailSent 
            ? "Welcome email sent to user" 
            : `Temporary password: ${result.tempPassword}`
        });
      } else {
        throw new Error("Failed to create user");
      }
    } catch (error) {
      toast({ title: "Failed to create user", variant: "destructive" });
    }
  };

  // Login form
  if (!isLoggedIn) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center p-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Card className="w-full max-w-md">
            <CardHeader className="text-center">
              <CardTitle className="text-2xl font-bold">Admin Access</CardTitle>
              <p className="text-muted-foreground">Sign in to manage content</p>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleLogin} className="space-y-4">
                <div className="space-y-2">
                  <div className="relative">
                    <User className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                    <Input
                      type="text"
                      placeholder="Username"
                      value={loginData.username}
                      onChange={(e) => setLoginData({ ...loginData, username: e.target.value })}
                      className="pl-10"
                      required
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <div className="relative">
                    <Lock className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                    <Input
                      type="password"
                      placeholder="Password"
                      value={loginData.password}
                      onChange={(e) => setLoginData({ ...loginData, password: e.target.value })}
                      className="pl-10"
                      required
                    />
                  </div>
                </div>
                <Button type="submit" className="w-full" disabled={isLoading}>
                  {isLoading ? "Signing in..." : "Sign In"}
                </Button>
              </form>

            </CardContent>
          </Card>
        </motion.div>
      </div>
    );
  }

  // Admin dashboard
  return (
    <div className="min-h-screen bg-background p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex justify-between items-center mb-8">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
          >
            <h1 className="text-3xl font-bold">Admin Dashboard</h1>
            <p className="text-muted-foreground">Manage your content and products</p>
          </motion.div>
          <div className="flex gap-2">
            <Button 
              onClick={() => window.location.href = "/"} 
              variant="outline"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Site
            </Button>
            <Button onClick={handleLogout} variant="outline">
              <LogOut className="h-4 w-4 mr-2" />
              Logout
            </Button>
          </div>
        </div>

        <Tabs defaultValue="products" className="space-y-6">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="products">
              <Package className="h-4 w-4 mr-2" />
              Products
            </TabsTrigger>
            <TabsTrigger value="users">
              <User className="h-4 w-4 mr-2" />
              Users
            </TabsTrigger>
          </TabsList>

          {/* Products Tab */}
          <TabsContent value="products" className="space-y-6">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-semibold">Product Management</h2>
              <Button onClick={() => setIsAddingProduct(true)}>
                Add New Product
              </Button>
            </div>

            {productsLoading ? (
              <div>Loading products...</div>
            ) : (
              <div className="grid gap-6">
                {products && Array.isArray(products) && products.map((product: Product) => (
                  <Card key={product.id}>
                    <CardHeader>
                      <div className="flex justify-between items-start">
                        <div>
                          <CardTitle className="flex items-center gap-2">
                            {product.name}
                            <Badge variant={product.status === "live" ? "default" : "secondary"}>
                              {product.status}
                            </Badge>
                          </CardTitle>
                          <p className="text-sm text-muted-foreground mt-1">
                            {product.abbreviation} • {product.category}
                          </p>
                        </div>
                        <div className="flex gap-2">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => setEditingProduct(product)}
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm mb-2">{product.description}</p>
                      {product.url && (
                        <p className="text-sm text-blue-600">URL: {product.url}</p>
                      )}
                      <p className="text-xs text-muted-foreground mt-2">
                        Position: ({product.positionX}, {product.positionY})
                      </p>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </TabsContent>

          {/* Users Tab */}
          <TabsContent value="users" className="space-y-6">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-semibold">User Management</h2>
              <div className="flex gap-2">
                <Button onClick={() => setIsChangingPassword(true)} variant="outline">
                  Change Password
                </Button>
                <Button onClick={() => setIsAddingUser(true)}>
                  Add User
                </Button>
              </div>
            </div>

            {usersLoading ? (
              <div>Loading users...</div>
            ) : (
              <div className="grid gap-4">
                {users && Array.isArray(users) && users.map((user: any) => (
                  <Card key={user.id}>
                    <CardHeader>
                      <div className="flex justify-between items-center">
                        <div>
                          <CardTitle>{user.username}</CardTitle>
                          <p className="text-sm text-muted-foreground">
                            Role: {user.role} • Created: {new Date(user.createdAt).toLocaleDateString()}
                          </p>
                          {user.email && (
                            <p className="text-sm text-muted-foreground">Email: {user.email}</p>
                          )}
                        </div>
                        <div className="flex gap-2">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => setEditingUser(user)}
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleDeleteUser(user.id)}
                            disabled={user.id === currentUser?.id}
                          >
                            <Trash className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </CardHeader>
                  </Card>
                ))}
              </div>
            )}
          </TabsContent>
        </Tabs>

        {/* Edit Product Modal */}
        {editingProduct && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
            <Card className="w-full max-w-2xl max-h-[90vh] overflow-y-auto">
              <CardHeader>
                <CardTitle>Edit Product</CardTitle>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleProductSubmit} className="space-y-4">
                  <div>
                    <label className="text-sm font-medium">Name</label>
                    <Input name="name" defaultValue={editingProduct.name} required />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Abbreviation</label>
                    <Input 
                      name="abbreviation" 
                      defaultValue={editingProduct.abbreviation} 
                      placeholder="Auto-generated from name"
                      required 
                    />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Description</label>
                    <Textarea name="description" defaultValue={editingProduct.description} required />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Category</label>
                    <Input name="category" defaultValue={editingProduct.category} required />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Status</label>
                    <select name="status" defaultValue={editingProduct.status} className="w-full p-2 border rounded bg-background text-foreground">
                      <option value="live">Live</option>
                      <option value="coming_soon">Coming Soon</option>
                      <option value="development">Development</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-sm font-medium">URL (optional)</label>
                    <Input name="url" defaultValue={editingProduct.url || ""} />
                  </div>

                  <div className="flex gap-2">
                    <Button type="submit" disabled={updateProductMutation.isPending}>
                      {updateProductMutation.isPending ? "Saving..." : "Save Changes"}
                    </Button>
                    <Button type="button" variant="outline" onClick={() => setEditingProduct(null)}>
                      Cancel
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Add New Product Modal */}
        {isAddingProduct && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
            <Card className="w-full max-w-2xl max-h-[90vh] overflow-y-auto">
              <CardHeader>
                <CardTitle>Add New Product</CardTitle>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleAddNewProduct} className="space-y-4">
                  <div>
                    <label className="text-sm font-medium">Name</label>
                    <Input 
                      name="name" 
                      placeholder="Product name" 
                      onChange={(e) => {
                        const abbField = e.target.form?.querySelector('[name="abbreviation"]') as HTMLInputElement;
                        if (abbField && !abbField.dataset.userModified) {
                          abbField.value = generateShortcode(e.target.value);
                        }
                      }}
                      required 
                    />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Abbreviation</label>
                    <Input 
                      name="abbreviation" 
                      placeholder="Auto-generated from name (can override)" 
                      onChange={(e) => {
                        e.target.dataset.userModified = "true";
                      }}
                    />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Description</label>
                    <Textarea name="description" placeholder="Product description" required />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Category</label>
                    <Input name="category" placeholder="Category" required />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Status</label>
                    <select name="status" defaultValue="development" className="w-full p-2 border rounded bg-background text-foreground">
                      <option value="live">Live</option>
                      <option value="coming_soon">Coming Soon</option>
                      <option value="development">Development</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-sm font-medium">URL (optional)</label>
                    <Input name="url" placeholder="https://..." />
                  </div>

                  <div className="flex gap-2">
                    <Button type="submit" disabled={createProductMutation.isPending}>
                      {createProductMutation.isPending ? "Creating..." : "Create Product"}
                    </Button>
                    <Button type="button" variant="outline" onClick={() => setIsAddingProduct(false)}>
                      Cancel
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Add User Modal */}
        {isAddingUser && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
            <Card className="w-full max-w-md">
              <CardHeader>
                <CardTitle>Add New User</CardTitle>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleUserSubmit} className="space-y-4">
                  <div>
                    <label className="text-sm font-medium">Username/Email</label>
                    <Input name="username" type="email" required />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Email (optional)</label>
                    <Input name="email" type="email" />
                  </div>
                  <div>
                    <label className="text-sm font-medium">Role</label>
                    <select name="role" className="w-full p-2 border rounded" required>
                      <option value="admin">Admin</option>
                      <option value="user">User</option>
                    </select>
                  </div>
                  <div className="flex gap-2">
                    <Button type="submit">Create User & Send Invite</Button>
                    <Button type="button" variant="outline" onClick={() => setIsAddingUser(false)}>
                      Cancel
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}